language: rust


matrix:
  include:
    - os:
        - linux
        - osx
        - windows
      rust:
        - stable
        - beta
        - nightly
    - os: linux
      rust:
        - stable
        - beta
        - nightly
      services: docker
      script:
        - cargo install cross
        - cross test --target i686-unknown-linux-gnu --verbose
    - os: linux # To compile for Windows x86
      rust:
        - stable
        - beta
        - nightly
      services: docker
      script:
        - cargo install cross
        - cross test --target i686-pc-windows-gnu --verbose