language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  -
  - NO_DEFAULT_FEATURES=1
  - NO_DEFAULT_FEATURES=1 FEATURES="std"

script:
  - [ ! -z "$NO_DEFAULT_FEATURES" ] && NO_DEFAULT_FEATURES="--no-default-features"
  - cargo test --verbose $NO_DEFAULT_FEATURES --features
  - cargo test --verbose --no-default-features --features "$FEATURES"