language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  -
  - NO_DEFAULT_FEATURES=1
  - NO_DEFAULT_FEATURES=1 FEATURES="std"

script:
  - cargo test --verbose $NO_DEFAULT_FEATURES --features "$FEATURES"