language: rust

services: docker

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  -
  - TARGET=i686-unknown-linux-gnu
  - TARGET=i686-pc-windows-gnu

script:
  - if [ -z "$TARGET" ]; then cargo test --verbose; fi
  - if [ ! -z "$TARGET" ]; then cargo install cross; cross test --target $TARGET --verbose; fi

matrix:
  exclude:
    - os: windows
      env: TARGET=i686-unknown-linux-gnu
    - os: windows
      env: TARGET=i686-pc-windows-gnu