language: rust

matrix:
  include:
    - os:
        - linux
        - osx
        - windows
      rust:
        - stable
        - beta
        - nightly
    - os: linux
      env:
        - TARGET=i686-unknown-linux-gnu
        - TARGET=i686-pc-windows-gnu
      rust:
        - stable
        - beta
        - nightly
      services: docker
      script:
        - cargo install cross
        - cross test --target $TARGET --verbose