language: rust

rust:
  - stable

os:
  - windows

matrix:
  include:
    - rust: stable
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      install:
        - rustup target add $TARGET
        - choco install msys2
        - pacman -S mingw-w64-x86_64-toolchain
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "C:\\\\tools\\\\msys64\\\\mingw64\\\\bin\\\\gcc.exe"\nar = "C:\\\\tools\\\\msys64\\\\mingw64\\\\bin\\\\ar.exe"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: beta
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup target add $TARGET
        - choco install msys2
        - pacman -S mingw-w64-x86_64-toolchain
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "C:\\\\tools\\\\msys64\\\\mingw64\\\\bin\\\\gcc.exe"\nar = "C:\\\\tools\\\\msys64\\\\mingw64\\\\bin\\\\ar.exe"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: nightly
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup target add $TARGET
        - choco install msys2
        - pacman -S mingw-w64-x86_64-toolchain
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "C:\\\\tools\\\\msys64\\\\mingw64\\\\bin\\\\gcc.exe"\nar = "C:\\\\tools\\\\msys64\\\\mingw64\\\\bin\\\\ar.exe"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET