language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

env:
  -
  - NO_DEFAULT_FEATURES=1
  - NO_DEFAULT_FEATURES=1 FEATURES="std"

script:
  - if [ "$NO_DEFAULT_FEATURES" = "1" ]; then NO_DEFAULT_FEATURES="--no-default-features"; else NO_DEFAULT_FEATURES=""; fi
  - cargo test --verbose $NO_DEFAULT_FEATURES --features "$FEATURES"