language: rust

rust:
  - stable

os:
  - windows

matrix:
  include:
    - rust: stable
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup set default-host $TARGET
        - rustup target add $TARGET
        - choco install -y mingw
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "C:\\\\ProgramData\\\\chocolatey\\\\lib\\\\mingw\\\\tools\\\\install\\\\mingw64\\\\bin\\\\x86_64-w64-mingw32-gcc"\nar = "C:\\\\ProgramData\\\\chocolatey\\\\lib\\\\mingw\\\\tools\\\\install\\\\mingw64\\\\bin\\\\x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: beta
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup set default-host $TARGET
        - rustup target add $TARGET
        - choco install -y mingw
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "C:\\\\ProgramData\\\\chocolatey\\\\lib\\\\mingw\\\\tools\\\\install\\\\mingw64\\\\bin\\\\x86_64-w64-mingw32-gcc"\nar = "C:\\\\ProgramData\\\\chocolatey\\\\lib\\\\mingw\\\\tools\\\\install\\\\mingw64\\\\bin\\\\x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: nightly
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup set default-host $TARGET
        - rustup target add $TARGET
        - choco install -y mingw
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "C:\\\\ProgramData\\\\chocolatey\\\\lib\\\\mingw\\\\tools\\\\install\\\\mingw64\\\\bin\\\\x86_64-w64-mingw32-gcc"\nar = "C:\\\\ProgramData\\\\chocolatey\\\\lib\\\\mingw\\\\tools\\\\install\\\\mingw64\\\\bin\\\\x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET