language: rust

rust:
  - stable

os:
  - windows

before_install: openssl aes-256-cbc -K $encrypted_9639d97fb148_key -iv $encrypted_9639d97fb148_iv -in github_repo_deploy_key.enc -out ~\/.ssh/github_repo_deploy_key -d

matrix:
  include:
    - rust: stable
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup target add $TARGET
        - choco install -y mingw
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-gcc"\nar = "/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: beta
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup target add $TARGET
        - choco install -y mingw
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-gcc"\nar = "/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET
    - rust: nightly
      os: windows
      env: TARGET=x86_64-pc-windows-gnu
      compiler: gcc
      install:
        - rustup target add $TARGET
        - choco install -y mingw
        - mkdir -p ~/.cargo
        - printf '\n[target.'$TARGET']\nlinker = "/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-gcc"\nar = "/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-ar"\n' >> ~/.cargo/config
      script: cargo test --target $TARGET